### ISSUE TITLE
Documentation - rspec ffmpeg dependency

### ISSUE THREAD

**Issue by ewlarson** [sciencehistory/kithe#107]
Cannot run the rspec suite successfully without ffmpeg installed. Should add a line to the dev notes in the README.

### Without ffmpeg

<img width="1181" alt="Screen Shot 2021-01-05 at 8 48 57 AM" src="https://user-images.githubusercontent.com/69827/103665437-0aed8300-4f39-11eb-8300-e02c7e7dc521.png">

### With ffmpeg

<img width="437" alt="Screen Shot 2021-01-05 at 9 35 56 AM" src="https://user-images.githubusercontent.com/69827/103665780-72a3ce00-4f39-11eb-8d48-687e5631c0f5.png">

**Comment by jrochkind** [comment]
Hi, I'm interested to see someone checking out this gem!  Would be interested in hearing more what you are interested in about it @ewlarson. 

OK, I see your point, thanks!
